// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQaoBZKAd-DH27_0ejcB-2FDciJGrwoHw',
    appId: '1:547837919842:web:98f48224b734b14a25473b',
    messagingSenderId: '547837919842',
    projectId: 'gearshift-app',
    authDomain: 'gearshift-app.firebaseapp.com',
    storageBucket: 'gearshift-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW46TcodLaO0t_wQih0rY2EgDtFkCpNjQ',
    appId: '1:547837919842:android:07d03ff2f55a138125473b',
    messagingSenderId: '547837919842',
    projectId: 'gearshift-app',
    storageBucket: 'gearshift-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD20j1dRErM50LwruBV8PJocGjYHhVJSdA',
    appId: '1:547837919842:ios:c4acb6ac9c0d4f7d25473b',
    messagingSenderId: '547837919842',
    projectId: 'gearshift-app',
    storageBucket: 'gearshift-app.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD20j1dRErM50LwruBV8PJocGjYHhVJSdA',
    appId: '1:547837919842:ios:c4acb6ac9c0d4f7d25473b',
    messagingSenderId: '547837919842',
    projectId: 'gearshift-app',
    storageBucket: 'gearshift-app.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQaoBZKAd-DH27_0ejcB-2FDciJGrwoHw',
    appId: '1:547837919842:web:f2bfa9003a6a045725473b',
    messagingSenderId: '547837919842',
    projectId: 'gearshift-app',
    authDomain: 'gearshift-app.firebaseapp.com',
    storageBucket: 'gearshift-app.firebasestorage.app',
  );
}
